--13.07.2018
SELECT ST.NAME, MIN(M.YEAR), MAX(M.YEAR), COUNT(*)
FROM STUDIO ST
JOIN MOVIE M ON M.STUDIONAME = ST.NAME
WHERE ST.NAME LIKE 'M%'
GROUP BY ST.NAME

SELECT TOP 1 MS.NAME, COUNT(*)
FROM MOVIESTAR MS
JOIN STARSIN S ON S.STARNAME = MS.NAME
WHERE MS.GENDER = 'F'
GROUP BY MS.NAME
ORDER BY COUNT(*) DESC

--10.09.2018
SELECT CL.CLASS, MIN(B.DATE), MAX(B.DATE), (CASE WHEN COUNT(B.NAME) > 0 THEN COUNT(B.NAME) ELSE NULL END)
FROM CLASSES CL
LEFT JOIN SHIPS S ON S.CLASS = CL.CLASS
LEFT JOIN OUTCOMES O ON O.SHIP = S.NAME
JOIN BATTLES B ON B.NAME = O.BATTLE
WHERE CL.CLASS LIKE 'N%'
GROUP BY CL.CLASS

SELECT O.BATTLE
FROM OUTCOMES O
JOIN SHIPS S ON O.SHIP = S.NAME
JOIN CLASSES C ON C.CLASS = S.CLASS
GROUP BY O.BATTLE
HAVING SUM(CASE WHEN C.TYPE = 'bb' THEN 1 ELSE 0 END) > SUM(CASE WHEN C.TYPE = 'bc' THEN 1 ELSE 0 END)

--09.07.2018
SELECT ST.NAME, MIN(M.YEAR), MAX(M.YEAR), COUNT(*)
FROM STUDIO ST
JOIN MOVIE M ON M.STUDIONAME = ST.NAME
WHERE ST.NAME LIKE 'M%'
GROUP BY ST.NAME


--05.08.2020
SELECT MS.NAME, MS.BIRTHDATE
FROM MOVIESTAR MS
JOIN STARSIN STIN ON STIN.STARNAME = MS.NAME
JOIN MOVIE MV ON MV.TITLE = STIN.MOVIETITLE AND MV.YEAR = STIN.MOVIEYEAR
WHERE MS.NAME NOT LIKE '%Jr.%'
GROUP BY MS.NAME, MS.BIRTHDATE
HAVING SUM(CASE WHEN MV.INCOLOR = 'Y' THEN 1 ELSE 0 END) > 0
ORDER BY MS.BIRTHDATE DESC, NAME ASC

SELECT MS.NAME, YEAR(MS.BIRTHDATE), COUNT(DISTINCT ST.NAME)
FROM MOVIESTAR MS
LEFT JOIN STARSIN STIN ON STIN.STARNAME = MS.NAME
LEFT JOIN MOVIE MV ON MV.TITLE = STIN.MOVIETITLE AND MV.YEAR = STIN.MOVIEYEAR
LEFT JOIN STUDIO ST ON ST.NAME = MV.STUDIONAME
WHERE MS.GENDER = 'F'
GROUP BY MS.NAME, MS.BIRTHDATE



--16.09.2020
SELECT ST.NAME, ST.ADDRESS
FROM STUDIO ST
JOIN MOVIE M ON M.STUDIONAME = ST.NAME
GROUP BY ST.NAME, ST.ADDRESS
HAVING SUM(CASE WHEN M.INCOLOR = 'Y' THEN 1 ELSE 0 END) > 0 AND SUM(CASE WHEN M.INCOLOR = 'N' THEN 1 ELSE 0 END) > 0
ORDER BY ST.ADDRESS ASC

SELECT ST.NAME, ST.ADDRESS, AVG(M.LENGTH) AS 'AVERAGE LENGTH'
FROM STUDIO ST
LEFT JOIN MOVIE M ON M.STUDIONAME = ST.NAME
GROUP BY ST.NAME, ST.ADDRESS
HAVING COUNT(*) <= 3





SELECT * FROM MOVIESTAR
SELECT * FROM STARSIN
SELECT * FROM MOVIE
SELECT * FROM STUDIO