/*SELECT TITLE, LENGTH 
FROM MOVIE
WHERE LENGTH=132 OR TITLE LIKE '%STAR%' OR TITLE='EMPIRE STRIKES BACK'

SELECT *
FROM MOVIE, STARSIN
WHERE MOVIE.TITLE=STARSIN.MOVIETITLE AND MOVIE.YEAR=STARSIN.MOVIEYEAR

SELECT *
FROM MOVIE

SELECT *
FROM MOVIE JOIN STARSIN
ON MOVIE.TITLE=STARSIN.MOVIETITLE AND MOVIE.YEAR=STARSIN.MOVIEYEAR

SELECT *
FROM MOVIE m JOIN STARSIN s
ON m.TITLE=s.MOVIETITLE AND m.YEAR=s.MOVIEYEAR

SELECT m.TITLE, s.STARNAME
FROM MOVIE m JOIN STARSIN s
ON m.TITLE=s.MOVIETITLE AND m.YEAR=s.MOVIEYEAR

SELECT * 
FROM MOVIE
WHERE LENGTH IS NOT NULL
ORDER BY LENGTH DESC, STUDIONAME ASC

SELECT CAST(42.66785 * 1.24 AS DECIMAL(10,8))

SELECT ADDRESS
FROM STUDIO
WHERE NAME = 'MGM'

SELECT BIRTHDATE
FROM MOVIESTAR
WHERE NAME = 'SANDRA BULLOCK'

SELECT si.STARNAME
FROM STARSIN si 
--JOIN MOVIE f
WHERE si.MOVIETITLE LIKE '%EMPIRE%' AND si.MOVIEYEAR=1980

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH>=10^7

SELECT NAME
FROM MOVIESTAR
WHERE GENDER='M' OR ADDRESS='MALIBU'

SELECT DISTINCT s.STARNAME
FROM MOVIE m
JOIN  STARSIN s ON m.TITLE=s.MOVIETITLE AND m.YEAR=s.MOVIEYEAR
WHERE STUDIONAME='Fox' AND m.TITLE LIKE '%Star%'*/

/*SELECT model,speed AS MHz,hd AS GB
FROM PC 
WHERE PRICE<=1200

SELECT MODEL, CAST(price * (1/1.1) AS DECIMAL(10,2)) AS euro
FROM PC
ORDER BY price DESC 

SELECT MODEL, HD, SCREEN
FROM laptop
WHERE price>=1000

SELECT *
FROM printer

SELECT *
FROM printer
WHERE color='y'

SELECT *
FROM pc

SELECT model, speed, hd
FROM pc
WHERE cd='12x' OR cd='16x' AND price<2000

SELECT code, model, CAST(speed+ram+10*screen AS int) AS rating
FROM laptop
ORDER BY rating DESC, code*/

SELECT *
FROM CLASSES

SELECT *
FROM SHIPS

SELECT *
FROM OUTCOMES

SELECT CLASS, COUNTRY
FROM CLASSES
WHERE NUMGUNS<10

SELECT NAME AS shipName
FROM SHIPS
WHERE LAUNCHED<1918

SELECT SHIP, BATTLE
FROM OUTCOMES
WHERE RESULT='SUNK'

SELECT NAME
FROM SHIPS
WHERE NAME=CLASS

SELECT NAME
FROM SHIPS
WHERE NAME LIKE 'R%'

SELECT NAME
FROM SHIPS
WHERE NAME LIKE '% %'