SELECT * FROM MOVIE
SELECT * FROM STARSIN
SELECT * FROM MOVIESTAR

SELECT ms.NAME,COUNT(DISTINCT m.STUDIONAME) AS STDNM
FROM MOVIESTAR ms
LEFT JOIN STARSIN si ON ms.NAME=si.STARNAME
LEFT JOIN MOVIE m ON m.TITLE=si.MOVIETITLE AND m.YEAR=si.MOVIEYEAR
GROUP BY ms.NAME

SELECT ms.NAME,COUNT(DISTINCT m.STUDIONAME) AS STDNM
FROM MOVIE m
JOIN STARSIN si ON m.TITLE=si.MOVIETITLE AND m.YEAR=si.MOVIEYEAR
RIGHT OUTER JOIN MOVIESTAR ms ON ms.NAME=si.STARNAME
GROUP BY ms.NAME

SELECT p.maker, 
	(SELECT COUNT(*) 
	FROM product p1 
	JOIN pc pc1 ON p1.model=pc1.model 
	WHERE p1.maker=p.maker) 
FROM product p
JOIN printer pr ON pr.model=p.model
WHERE pr.type='Laser'
GROUP BY p.maker
HAVING COUNT(*)>=2

SELECT p.maker, COUNT(*)
FROM product p
JOIN pc ON p.model=pc.model
WHERE p.maker IN 
				(SELECT p1.maker 
				FROM product p1 
				LEFT JOIN printer pr ON pr.model=p1.model
				WHERE pr.type='Laser'
				GROUP BY p1.maker 
				HAVING COUNT(*)>=2)
GROUP BY p.maker


SELECT YEAR(b.DATE), COUNT(DISTINCT s.NAME)
FROM BATTLES b
JOIN SHIPS s ON YEAR(b.DATE) = s.LAUNCHED
GROUP BY YEAR(b.DATE)

SELECT s.LAUNCHED, COUNT(s.LAUNCHED)
FROM BATTLES b
JOIN SHIPS s ON YEAR(b.DATE) = s.LAUNCHED
GROUP BY s.LAUNCHED


SELECT o.BATTLE, c.COUNTRY, COUNT(o.BATTLE) AS C
FROM OUTCOMES o
JOIN SHIPS s ON s.NAME=o.SHIP
JOIN CLASSES c ON c.CLASS=s.CLASS
WHERE o.RESULT='sunk'
GROUP BY o.BATTLE, c.COUNTRY

SELECT o.BATTLE, COUNT(*) AS C
FROM OUTCOMES o
JOIN SHIPS s ON s.NAME=o.SHIP
JOIN CLASSES c ON c.CLASS=s.CLASS
WHERE o.RESULT='sunk' AND c.COUNTRY='USA'
GROUP BY o.BATTLE


SELECT c.COUNTRY, 
					SUM(CASE o.RESULT 
						WHEN 'damaged' 
						THEN 1 
						ELSE 0 END) AS DMG,
					SUM(CASE o.RESULT 
						WHEN 'sunk' 
						THEN 1 
						ELSE 0 END) AS SUNK
FROM CLASSES c
LEFT JOIN SHIPS s ON s.CLASS=c.CLASS
LEFT JOIN OUTCOMES o ON o.SHIP=s.NAME
GROUP BY c.COUNTRY

SELECT c.COUNTRY, COUNT(o1.RESULT) AS DMG, COUNT(o2.RESULT) AS SUNK
FROM CLASSES c
LEFT JOIN SHIPS s ON s.CLASS=c.CLASS
LEFT JOIN OUTCOMES o1 ON o1.SHIP=s.NAME AND o1.RESULT='damaged'
LEFT JOIN OUTCOMES o2 ON o2.SHIP=s.NAME AND o2.RESULT='sunk'
GROUP BY c.COUNTRY


SELECT o.BATTLE, 
				COUNT(DISTINCT o.SHIP) AS WITHNUMGUNSLESSTHAN9, 
				COUNT(DISTINCT o2.SHIP) AS WEREOK
FROM OUTCOMES o
JOIN SHIPS s ON o.SHIP=s.NAME
JOIN CLASSES c ON c.CLASS=s.CLASS
JOIN OUTCOMES o2 ON o2.BATTLE=o.BATTLE AND o2.RESULT='ok'
WHERE c.NUMGUNS<=9
GROUP BY o.BATTLE
HAVING COUNT(DISTINCT o.SHIP)>=3 AND COUNT(DISTINCT o2.SHIP)>=2