SELECT DISTINCT ms.NAME
FROM MOVIESTAR ms
JOIN MOVIEEXEC me ON me.NAME!=ms.NAME

SELECT *
FROM product pd
JOIN printer pr ON pd.model=pr.model AND pd.type='Printer'
WHERE pr.price=(SELECT MIN(price) FROM printer)


SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL (SELECT NUMGUNS FROM CLASSES)

SELECT o.BATTLE
FROM OUTCOMES o
WHERE o.SHIP IN (SELECT NAME FROM SHIPS WHERE CLASS='Kongo')




SELECT C.COUNTRY,S.NAME
FROM CLASSES C
JOIN SHIPS S ON S.CLASS=C.CLASS
LEFT JOIN OUTCOMES o ON o.SHIP=s.NAME
WHERE o.BATTLE IS NULL
ORDER BY C.COUNTRY



SELECT pr.maker,pr.model,pr.type
FROM PRODUCT pr
LEFT JOIN PC p ON p.model=pr.model
WHERE p.model IS NULL AND pr.type='PC'
UNION
SELECT pr.maker,pr.model,pr.type
FROM PRODUCT pr
LEFT JOIN laptop p ON p.model=pr.model
WHERE p.model IS NULL AND pr.type='Laptop'
UNION
SELECT pr.maker,pr.model,pr.type
FROM PRODUCT pr
LEFT JOIN printer p ON p.model=pr.model
WHERE p.model IS NULL AND pr.type='Printer'

--НЕ МОЖЕ ТАКА!
SELECT maker, model, type
FROM product
WHERE 
CASE type
	WHEN 'PC' THEN model NOT IN (SELECT model FROM pc)
    WHEN 'Laptop' THEN model NOT IN (SELECT model FROM laptop)
    ELSE model NOT IN (SELECT model FROM printer)
END;

SELECT speed, AVG(price) AS AVGPRC
FROM PC
GROUP BY speed
HAVING speed>=300

SELECT AVG(p.price) as PCAVG, AVG(l.price) as LAVG, (AVG(p.price)+AVG(l.price))/2 as TOTAVG
FROM product pr
LEFT JOIN PC p ON p.model=pr.model AND pr.type='PC'
LEFT JOIN laptop l ON l.model=pr.model AND pr.type='Laptop'
WHERE pr.maker='B'
GROUP BY pr.maker

SELECT screen, MAX(price),MIN(price),MAX(price)-MIN(price)
FROM laptop
GROUP BY screen

SELECT COUNT(*)
FROM CLASSES

SELECT s.CLASS, (CASE
		WHEN o.RESULT='sunk' THEN 1
		ELSE 0
		END) AS SUNKMT4
FROM SHIPS s
LEFT JOIN OUTCOMES o ON o.SHIP=s.NAME
GROUP BY s.CLASS,o.RESULT
HAVING COUNT(*)>=4


SELECT YEAR(b.DATE), COUNT(s.NAME)
FROM BATTLES b
   LEFT OUTER JOIN SHIPS s ON YEAR(b.DATE) = s.LAUNCHED
GROUP BY YEAR(b.DATE)

SELECT c.COUNTRY, COUNT(o.ship) AS DMG, COUNT(o2.ship) AS SNK
FROM CLASSES c
LEFT JOIN SHIPS s ON c.CLASS=s.CLASS
LEFT JOIN OUTCOMES o ON o.SHIP=s.NAME AND o.RESULT='damaged'
LEFT JOIN OUTCOMES o2 ON o2.SHIP=s.NAME AND o2.RESULT='sunk'
GROUP BY c.COUNTRY

SELECT o.BATTLE
FROM OUTCOMES o
JOIN SHIPS s ON s.NAME=o.SHIP
JOIN CLASSES c ON c.CLASS=s.CLASS
WHERE c.NUMGUNS>=9
GROUP BY o.BATTLE
HAVING COUNT(o.SHIP)>=3 AND SUM(CASE o.RESULT WHEN 'ok' THEN 1 ELSE 0 END)>=2 

SELECT c.CLASS, COUNT(*)
FROM CLASSES c
JOIN SHIPS s ON s.CLASS=c.CLASS
GROUP BY c.CLASS
HAVING MAX(s.LAUNCHED)<=1921

SELECT o.BATTLE,COUNT(DISTINCT oo.SHIP) AS OK,COUNT(DISTINCT od.SHIP) AS DMG,COUNT(DISTINCT os.SHIP) AS SNK
FROM OUTCOMES o
LEFT JOIN OUTCOMES oo ON oo.BATTLE=o.BATTLE AND oo.RESULT='ok'
LEFT JOIN OUTCOMES od ON od.BATTLE=o.BATTLE AND od.RESULT='damaged'
LEFT JOIN OUTCOMES os ON os.BATTLE=o.BATTLE AND os.RESULT='sunk'
GROUP BY o.BATTLE

SELECT *
FROM OUTCOMES o
LEFT JOIN OUTCOMES oo ON oo.BATTLE=o.BATTLE AND oo.RESULT='ok'
LEFT JOIN OUTCOMES od ON od.BATTLE=o.BATTLE AND od.RESULT='damaged'
LEFT JOIN OUTCOMES os ON os.BATTLE=o.BATTLE AND os.RESULT='sunk'
ORDER BY o.BATTLE


