--Movie
SELECT * FROM MOVIE
SELECT * FROM MOVIESTAR
SELECT * FROM MOVIEEXEC
SELECT * FROM STARSIN
SELECT * FROM STUDIO

--PC
SELECT * FROM product
SELECT * FROM pc
SELECT * FROM laptop
SELECT * FROM printer


--Ships
SELECT * FROM CLASSES
SELECT * FROM SHIPS ORDER BY CLASS
SELECT * FROM OUTCOMES
SELECT * FROM BATTLES


SELECT * FROM product pr
LEFT JOIN pc p ON p.model=pr.model AND pr.type='PC' 
LEFT JOIN laptop l ON l.model=pr.model AND pr.type='Laptop'
